#!/bin/bash

# Verifica se a Norminette está instalada
if ! command -v norminette &> /dev/null
then
    echo "Norminette não encontrada. Instale-a antes de continuar."
    exit 1
fi

# Função para exibir texto colorido
print_colored() {
    case $2 in
        "greenb") echo -e "\033[1;32m$1\033[0m" ;; # Verde
        "yellowb") echo -e "\033[1;33m$1\033[0m" ;; # Amarelo
        "yellow") echo -e "\033[0;33m$1\033[0m" ;; # Amarelo
        *) echo "$1" ;; # Sem cor
    esac
}

# Verifica se a flag -D foi passada
SHOW_ALL=false
if [[ "$1" == "-D" ]]; then
    SHOW_ALL=true
fi

FOUND_ERROR=false

# Rodar norminette e filtrar arquivos com ou sem erro
for file in $(find . -type f \( -name "*.c" -o -name "*.h" \)); do
    output=$(norminette "$file")
    
    if echo "$output" | grep -q "Error"; then
        # Arquivo com erro (KO)
	FOUND_ERROR=true
        if $SHOW_ALL; then
            print_colored "KO: $file" "yellowb"
	    print_colored "$output" "yellow"
        else
            print_colored "KO: $file" "yellowb"
	    print_colored "$output" "yellow"
        fi
    else
        # Arquivo sem erro (OK)
        if $SHOW_ALL; then
            print_colored "OK: $file" "greenb"
        fi
    fi
done

if ! $FOUND_ERROR && ! $SHOW_ALL; then
	print_colored ">>>>> SUCCESS <<<<<" "greenb"
fi

